### ISSUE TITLE
:octocat: github api handler 

### ISSUE THREAD

**Issue by wooleejaan** [wooleejaan/august-archive#10]
### Description

github api handler

### To-do

- [ ] creating github api handlers
- [ ] injecting handlers into server components
- [ ] applying ISR(Incremental Static Regeneration) to github api handlers
