### ISSUE TITLE
:octocat: issue that creates common components for post

### ISSUE THREAD

**Issue by wooleejaan** [wooleejaan/august-archive#12]
### Description

issue that creates a common component for post

### To-do

페이지 내부
- [x] Heading Component (h1, h2, h3) `Post.H1`, `Post.H2`, `Post.H3`
- [x] Spacing Component `Post.SP`
- [x] Paragraph Component (that can be color-injected) `Post.P`
- [x] Image Component (that can handle various image sizes and numbers.) `Post.I`
- [x] YoutubeVideo Component `Post.Y`
- [x] Sources Component `Post.SR`
- [x] CodeContainer Component `Post.C`

페이지 내/외부 
- [x] Tags
