### ISSUE TITLE
:octocat: issue implements the api handler

### ISSUE THREAD

**Issue by wooleejaan** [wooleejaan/august-archive#29]
### Description

issue implements the api handler

1. `getPreview()` 
2. `getItems()`
3. `getItemDetail()` 

### To-do

- [ ] path : "/" 
  - [ ] GET /contents/preview/posts
  - [ ] GET /contents/preview/projects
- [ ] path : "/posts"
  - [ ] list : GET /contents/posts/1
  - [ ] detail : GET /contents/posts/1/{post title}.mdx
- [ ] path : "/projects"
  - [ ] list : GET /contents/projects/11
  - [ ] detail : GET /contents/projects/11/{project title}.mdx
